### ISSUE TITLE
Ошибка сборки сервера

### ISSUE THREAD

**Issue by vender** [kolserdav/react-node-webrtc-sfu#18]
При сборки сервера ошибка.
`Error: Cannot find module '../types/interfaces'`
При этом почему-то в .gitignore есть
`src/types/interfaces.ts`

**Comment by kolserdav** [comment]
Как я понимаю Вы клонировали проект через `git clone https://github.com/kolserdav/werift-sfu-react` и пытаетесь собрать сервер командой `npm run build:server`!? Если так, то причина в том, что не скопированы общие клиент-серверные типы, они копируются при запуске команды `npm install` из корневой папки так как только там прописан `postinstall` https://github.com/kolserdav/werift-sfu-react/blob/ed661c49a05a6b1409f89e75216aa01c44135fd7/package.json#L82 . А вы наверное устанавливали зависимости из `packages/server` поэтому копирование интерфейсов не сработало.

**Comment by vender** [comment]
Спасибо за ответ, проблема была в том что из под винды не хватало прав на postinstall.

**Comment by kolserdav** [comment]
Обновите свою установку, сегодня пробовал запускать из Windows и сделал ряд исправлений.

**Comment by vender** [comment]
Столкнулся с еще одной проблемой, видимо что-то делаю не так
`
npm run start

> server@1.0.0 start
> npm run migrate && node index.js


> server@1.0.0 migrate
> uyem --db mysql://root:root@127.0.0.1:3306/uyem_db --migrate

 info  uyem@0.14.17 started  ...
 info  Set up Simple-CORS defence:

 info  Set up database url:  mysql://root:root@127.0.0.1:3306/uyem_db

 info  Using database url:  mysql://root:••••@127.0.0.1:3306/uyem_db

 info  Start migrate only script...

 info  Running "npm run migrate" command...
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'run', 'migrate' ]
}

Node.js v18.12.1
`

окружение Docker из инструкции по установке

**Comment by kolserdav** [comment]
Вы наверное скачивали релиз тогда не сработает обновление через
```sh
git pull origin master
```
В версии https://github.com/kolserdav/werift-sfu-react/releases/tag/v1.0.8 эта проблема исправлена

**Comment by vender** [comment]
Еще вот такая ошибка уже на сервере вылезла
`
error  uncaughtException  TypeError: Cannot destructure property 'createServer' of 'require(...).default' as it is undefined.
    at Object.<anonymous> (/www/wwwroot/server/node_modules/uyem/server.js:1:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/www/wwwroot/server/index.js:2:26)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
`

**Comment by kolserdav** [comment]
`.default` не нужен в `require` и вот я проверял на 18 ноде, в этой версии с правками https://github.com/kolserdav/werift-sfu-react/releases/tag/v1.1.2
